on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:

name: build
jobs:
  build:
    name: build
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install packages (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake gcc g++ make

      - name: Build
        shell: bash
        run: bash build_static.sh

      - name: Build artifact
        shell: bash
        run: |
          rm -r src/printemps/build
          make -C src/runsolver/src clean
          mkdir -p dest/printemps-pb
          cp -a LICENSE README.md bin build.sh build_static.sh src dest/printemps-pb/
          cd dest
          find . -name ".git" -exec rm -rf {} +
          tar zcf ../printemps-pb.tar.gz printemps-pb

      - name: ldd
        run: |
          # The `ldd` command is used to check the shared library dependencies of the binaries.
          # Failures are ignored (`|| true`) because the binaries are expected to be statically linked,
          # and missing shared libraries are not an issue in this case.
          echo "ldd bin/pb_competition_2025_solver"
          ldd bin/pb_competition_2025_solver || true
          echo "ldd bin/runsolver"
          ldd bin/runsolver || true

      - name: Check that pb_competition_2025_solver works
        run: |
          bin/pb_competition_2025_solver samples/mult.opb

      - name: Check that runsolver + pb_competition_2025_solver works
        run: |
          set -x
          bin/runsolver -d 5 -C $((10-5-1)) -W $((10-5-1)) -v out.v -w out.w bin/pb_competition_2025_solver -k 1000000 -r 1 samples/mult.opb
          cat out.v
          cat out.w

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: binary-packages
          path: printemps-pb.tar.gz
